---
title: "Institutional decision-making"
subtitle: ""
date: "2022-07-14"
draft: true
categories: 
  - policy
  - governance
  - decision-making
format: 
  html: 
    toc: true
    code-link: true
    code-fold: show
    code-tools: true
    comments:
      hypothesis: true
---

The existential challenges of modern society sometimes feel insurmountable, and perhaps when the problems are as big as climate crises, pandemics, and global conflicts, solutions should feel out of reach for individuals. Instead it is institutions like governments and corporations which wield enough power to affect change But it's clear even in our recent past that coordinating human effort through institutions like governments. And it is But when individuals and communities form institutionsinto

to Improving how our institutions make decisions is one of most broadly impactful issues we can address today. The last five decades of behavioural science research has greatly expanded our understanding of judgement and decision-making, and where and how errors can occur in our thinking. We have tested various interventions for the past few decades in the form of *nudges*, or *boosts*, to get a better understanding of the contextual factors that help or hinder decisions. Identifying and evaluating institutions which suffer from error-prone decision mechanisms could . A world with more effective institutions is one in which we can address problems, coordinate resources, and improve the quality of life across the globe.

Governance institutions around the world appear to be struggling to address modern challenges as they morph from *changes* to *crises*. In the US, legislators have squarely failed to address several ongoing crises from homelessness to global warming amidst a bleak backdrop of racial injustice and deepening political divides. The credibility of the governing institutions is deteriorating as the response to a global pandemic was slow and lackluster, the scientific community repeatedly warns of catastrophic environmental risks, and civil society struggles with economic inequality amidst growing corporate influence.

Congress seems to be struggling to pass laws in the first place, regardless of the individual law's effectiveness. It is troubling when significant legislative efforts, like the Inflation Reduction Act, only has support from one side of the aisle. One would hope the legislative process improves the quality of legislation as a bill goes from idea to law, and that the institution itself would get better at not only drafting legislation, but debating and revising it too.

Questions I want to answer:

-   What parts of the legislative process rely on human judgement?\
    Obviously a lot, but what are the discrete decisions made through the committees, on the floor, and in between.

-   Are there elements of the decision-making context, for which there is evidence of bias, noise, or decision-hygiene interventions?

-   What kind of options are there for studying decision-making in legislatures?
